[build]
  publish = "."
  command = "echo done"
  ignore = "exit 0"

[build.environment]
  NETLIFY_SKIP_PYTHON_SETUP = "1"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
