[build]
builder = "nixpacks"

[build.nixpacks]
pkgs = ["python312", "python312Packages.pip"]

[[services]]
name = "streaklyapp"

[services.build]
buildCommand = "pip install -r railway-requirements.txt"

[services.deploy]
startCommand = "python bot/main.py"

[[services]]
name = "backend"

[services.build]
buildCommand = "pip install -r railway-requirements.txt"

[services.deploy]
startCommand = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
